-- AlterTable
ALTER TABLE `recipe` ADD COLUMN `isFavorite` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `origin` VARCHAR(191) NULL,
    ADD COLUMN `rating` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `servings` INTEGER NOT NULL DEFAULT 4;
